
networks:
  apps:
    name: "compose_apps"
    external: true

services:
  gluetun:
    labels:
      backup: true
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      apps:
        ipv4_address: ${MACVLAN_GLUETUN_IP}
    ports:
      - 3000:3000 # rdesktop
      - 3001:3001
    volumes:
      - ${DOCKER_DIR}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - DOT=off
      - DNS_ADDRESS=1.1.1.1
      - WIREGUARD_PRIVATE_KEY=${SURFSHARK_PRIVATE_KEY}
      - WIREGUARD_PUBLIC_KEY=${SURFSHARK_PUBLIC_KEY}
      - WIREGUARD_ADDRESSES=${SURFSHARK_ADDRESS}
      - SERVER_COUNTRIES=${SURFSHARK_COUNTRIES}

  rdesktop:
    labels:
      backup: true
      caddy: rdesktop.muletto.colasuonno.net
      caddy.reverse_proxy: gluetun:3000
    restart: unless-stopped
    image: lscr.io/linuxserver/firefox:latest
    container_name: rdesktop
    network_mode: service:gluetun
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DRINODE=/dev/dri/renderD128
      - NO_FULL=true
      - START_DOCKER=false
      - FM_HOME=/downloads
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=wget|megatools|openjdk-17-jre|libmediainfo0v5|fonts-dejavu|bash|lxterminal|transmission|xrdp|thunar|adwaita-icon-theme|wireguard-tools|python3|python3-requests|pkexec|policykit-1|psmisc|python3-packaging|python3-psutil|python3-xdg
    volumes:
      - ${DOCKER_DIR}/rdesktop/config:/config
      - ${MERGERFS_ROOT}/Media:/media
      - ${MERGERFS_ROOT}/Downloads:/downloads
    shm_size: 1gb
